Vagrant.configure("2") do |config|
  config.vm.define "shelepen"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "2.4.8.2"
  config.vm.provider "virtualbox" do |v|
    #v.gui = true
    v.memory = 2048
    v.cpus = 3
  end
  config.vm.synced_folder "../public_html", "/var/www/shelepen/public_html",
    :owner => "www-data",
    :group => "www-data",
    :mount_options => ["dmode=775","fmode=664"]
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "provisioning/inventory"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.verbose = "vvvv"
    ansible.sudo = true
  end
end
